# Generated by Django 5.0.2 on 2024-02-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]
