# Generated by Django 5.0.2 on 2024-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpersonal',
            name='computadora_funciona',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='conocimientos_programacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='tiene_computadora',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='tiene_cortes_energia',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='tiene_internet',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='tiene_telefono_propio',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3),
        ),
    ]
